#!/usr/bin/env php
<?php

/**
 * The directory in which your application specific resources are located.
 * The application directory must contain the bootstrap.php file.
 *
 * @see  http://kohanaframework.org/guide/about.install#application
 */
$application = realpath(getcwd().DIRECTORY_SEPARATOR.'application');

/**
 * The directory in which your modules are located.
 *
 * @see  http://kohanaframework.org/guide/about.install#modules
 */
$modules = realpath(getcwd().DIRECTORY_SEPARATOR.'modules');

/**
 * The directory in which the Kohana resources are located. The system
 * directory must contain the classes/kohana.php file.
 *
 * @see  http://kohanaframework.org/guide/about.install#system
 */
$system = realpath(getcwd().DIRECTORY_SEPARATOR.'system');

/**
 * The default extension of resource files. If you change this, all resources
 * must be renamed to use the new extension.
 *
 * @see  http://kohanaframework.org/guide/about.install#ext
 */
define('EXT', '.php');

/**
 * Set the path to the document root
 *
 * This assumes that this file is stored 2 levels below the DOCROOT, if you move 
 * this bootstrap file somewhere else then you'll need to modify this value to 
 * compensate.
 */
define('DOCROOT', realpath(getcwd().DIRECTORY_SEPARATOR.'web'.DIRECTORY_SEPARATOR));

/**
 * Set the PHP error reporting level. If you set this in php.ini, you remove this.
 * @see  http://php.net/error_reporting
 *
 * When developing your application, it is highly recommended to enable notices
 * and strict warnings. Enable them by using: E_ALL | E_STRICT
 *
 * In a production environment, it is safe to ignore notices and strict warnings.
 * Disable them by using: E_ALL ^ E_NOTICE
 *
 * When using a legacy application with PHP >= 5.3, it is recommended to disable
 * deprecated notices. Disable with: E_ALL & ~E_DEPRECATED
 */
error_reporting(E_ALL | E_STRICT);

/**
 * End of standard configuration! Changing any of the code below should only be
 * attempted by those with a working knowledge of Kohana internals.
 *
 * @see  http://kohanaframework.org/guide/using.configuration
 */

// Make the application relative to the docroot
if ( ! is_dir($application) AND is_dir(DOCROOT.$application))
{
	$application = DOCROOT.$application;
}

// Make the modules relative to the docroot
if ( ! is_dir($modules) AND is_dir(DOCROOT.$modules))
{
	$modules = DOCROOT.$modules;
}

// Make the system relative to the docroot
if ( ! is_dir($system) AND is_dir(DOCROOT.$system))
{
	$system = DOCROOT.$system;
}

// Define the absolute paths for configured directories
define('APPPATH', realpath($application).DIRECTORY_SEPARATOR);
define('MODPATH', realpath($modules).DIRECTORY_SEPARATOR);
define('SYSPATH', realpath($system).DIRECTORY_SEPARATOR);

// Clean up the configuration vars
unset($application, $modules, $system);


define('CLI', getcwd());

include_once getcwd().DIRECTORY_SEPARATOR."application".DIRECTORY_SEPARATOR."bootstrap.php";

try{
	if ( ! (php_sapi_name() == 'cli' && empty($_SERVER['REMOTE_ADDR'])) )
	{
		throw new Kohana_Exception("This can only be executed from the command line");
	}

	if( ! isset($argv[1]) OR ($argv[1] == 'help' AND ! isset($argv[2])))
	{
		Command::log("Command Line Kohana Tool");
		Command::log("  ".Command::colored("list", "green")." - list commnads");
		Command::log("  ".Command::colored("help {command}", "green")." - get help for command");
		Command::log("  ".Command::colored("{command}", "green")." - run the command");
	}
	elseif( $argv[1] == 'list')
	{
		$files = Kohana::list_files('command');
		foreach($files as $filename => $file)
		{
			$name = pathinfo($filename, PATHINFO_FILENAME);
			require_once $file;
			
			$class = new ReflectionClass('Command_'.ucfirst($name));

			Command::log($name, "brown");

			foreach($class->getMethods() as $method)
			{
				if($method->isPublic() AND ! $method->isConstructor() AND ! $method->isDestructor() AND $method->getDeclaringClass()->getName() == $class->getName())
				{
					Command::log(
						"  ".
						Command::colored(str_pad($name.':'.str_replace('_', ':', $method->getName()), 38, " ", STR_PAD_RIGHT), "green"). 
						$class->getConstant(strtoupper($method->getName()."_brief"))
					);
				}
			}
		}
	}
	elseif($argv[1] == 'help')
	{
		$arguments = explode(':', $argv[2]);

		$class = new ReflectionClass(Command::load_command_file($arguments[0]));

		$method_name = isset($arguments[1]) ? join('_', array_slice($arguments,1)) : 'index';

		$description = $class->getConstant(strtoupper("{$method_name}_desc"));
		if( ! $description)
		{
			$description = $class->getConstant(strtoupper("{$method_name}_brief"));
		}
		if( ! $description)
		{
			$description = "Missing description";
		}
		
		Command::log($argv[2], "brown");
		Command::log($description);
	}
	else
	{
		$options = Command_Options::factory()->populate_from_argv();

		$method_arguments = array($argv[1], $options);
		foreach(array_slice($argv, 2) as $argument)
		{
			if(substr($argument, 0, 2) !== '--')
			{
				$method_arguments[] = $argument;
			}
		}

		call_user_func_array('Command::execute', $method_arguments);
	}
}
catch( Exception $e)
{
	if(Kohana::$config->load('cli.capture_exceptions'))
	{
		Command::log(Kohana_Exception::text($e), Command::ERROR);	
	}
	else
	{
		throw $e;
	}
}
