#!/bin/bash

find ../web -type f -follow -regex "\.\.\/web\/upload\/image\/group-[0-9]+\/[0-9]*\/[^\/]*\.[jpengif]*$"|
while read f
do
  echo "Processing $f"
  mogrify -resize 430x600 -gravity center -path `dirname "$f"`/list/ "$f"
  echo "Finished with $f"  
done
